name: Build LaTeX Resume

on:
  push:
    branches: [ main ]

jobs:
  latex:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode resume/main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: resume/main.pdf
