name: Publish Resume to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        uses: docker://ghcr.io/xu-cheng/texlive-full:latest
        with:
          args: pdflatex -interaction=nonstopmode main.tex

      - name: Push to Pages Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/${{ github.repository_owner }}/cv.git pages
          cp main.pdf pages/resume.pdf
          cd pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update resume $(date '+%Y-%m-%d %H:%M')"
          git push
